package com.github.ioc;

import java.io.IOException;
import java.lang.reflect.Field;
import java.util.*;
import java.util.stream.Collectors;
import java.util.stream.Stream;

public class MyIocContainer {
    public static void main(String[] args) throws IOException {
        // load all bean information
        Properties properties = new Properties();
        properties.load(MyIocContainer.class.getResourceAsStream("/ioc.properties"));

        // generate a ioc container get put bean instance generated by reflection into this container
        Map<String, Object> beans = new HashMap<>();
        properties.forEach((beanName, beanClass) -> {
            try {
                Class klass = Class.forName((String) beanClass);
                Object beanInstance = klass.getConstructor().newInstance();
                beans.put((String) beanName, beanInstance);
            } catch (Exception e) {
                throw new RuntimeException(e);
            }
        });

        beans.forEach((beanName, beanInstance) -> {
            dependencyInject(beanName, beanInstance, beans);
        });

        // for certification
        OrderService orderService =(OrderService) beans.get("orderService");
        OrderDao orderDao =(OrderDao) beans.get("orderDao");
        System.out.println();

    }

    private static void dependencyInject(String beanName, Object beanInstance, Map<String, Object> beans) {
        List<Field> fieldsToBeAutoWired = Stream.of(beanInstance.getClass().getDeclaredFields())
                .filter(field -> field.getAnnotation(Autowired.class) != null)
                .collect(Collectors.toList());

        fieldsToBeAutoWired.forEach(field -> {
            try {
                String fieldName = field.getName();
                Object dependencyBeanInstance = beans.get(fieldName);
                field.setAccessible(true);
                field.set(beanInstance, dependencyBeanInstance);
            } catch (IllegalAccessException e) {
                throw new RuntimeException(e);
            }
        });
    }
}
